### ISSUE TITLE
Handle y-x CRS axis ordering

### ISSUE THREAD

**Issue by letmaik** [fsvieira/map2covjson#1]
There are CRSs where the axis order is flipped (y,x instead of x,y). This has to be reflected in the `domain.referencing[..].coordinates` array which would then be `["y", "x"]`. Everything else stays the same.

I think the following two functions could be used for that:

[`int OGRSpatialReference::EPSGTreatsAsLatLong()`](http://www.gdal.org/classOGRSpatialReference.html#a519cce70fd39f974c61342bf73ab01ad)
[`int OGRSpatialReference::EPSGTreatsAsNorthingEasting()`](http://www.gdal.org/classOGRSpatialReference.html#a2fe484ea1e7c8e8121b3ae05bb1a1878)

So, if either of those returns true, then use `["y", "x"]` as value, otherwise `["x", "y"]`.

@jonblower Do you happen to have an example of a flipped projected CRS?

**Comment by fsvieira** [comment]
Hi, thanks, I didn't know that.

I will fix it, if @jonblower could provide an example it would be great for testing, otherwise I will try to find one.

**Comment by jonblower** [comment]
Well, EPSG:4326 is left-handed (lat then lon) and CRS:84 is the right-handed equivalent (lon then lat), although tools are quite inconsistent in respecting this.

I think there are also left- and right-handed versions of several projections, including polar stereographic ones. I'm afraid I can't find specific example right now, but have a look around on Google perhaps.

**Comment by fsvieira** [comment]
I am having some trouble with this, 

int OGRSpatialReference::EPSGTreatsAsLatLong()
int OGRSpatialReference::EPSGTreatsAsNorthingEasting()

are always returning 0 for my examples, and I think its wrong, my test files are y, x.

The GetAxis function return NULL, and checking the projection string I don't see any information for the axis order. I also try some of the files in here: ftp://ftp.remotesensing.org/pub/geotiff/samples

I guess this is a tricky problem:
https://trac.osgeo.org/gdal/wiki/rfc20_srs_axes

I will try to ask on OSGeo.

**Comment by letmaik** [comment]
Which epsg code do your projections have? I'd like to check it manually.

**Comment by fsvieira** [comment]
Hi,

I made a test case with the projection strings here:
https://github.com/fsvieira/map2covjson/blob/fv-test-projections/projection_tests.cpp#L37

The first one is from my raster, the other ones are taken from the spatialreference.org

And this is my program output:
Projection = PROJCS["WGS 84 / UTM zone 29N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-9],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AUTHORITY["EPSG","32629"]]
AUTHORITY = EPSG:32629
EPSGTreatsAsLatLong = False
Axis Order = Long, Lat ("x", "y")

Projection = PROJCS["WGS 84 / UTM zone 29N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-9],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],AUTHORITY["EPSG","32629"],AXIS["Easting",EAST],AXIS["Northing",NORTH]]
AUTHORITY = EPSG:32629
EPSGTreatsAsLatLong = False
Axis Order = Long, Lat ("x", "y")

Projection = GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
AUTHORITY = EPSG:4326
EPSGTreatsAsLatLong = False
Axis Order = Long, Lat ("x", "y")

I don't know if I am doing something wrong or if this is a gdal bug.

**Comment by letmaik** [comment]
The first two are the same, and they are in easting-northing order, see https://epsg.io/32629. The last one is in latitude, longitude order. So, since the UTM one (the first one) is not geographical but projected coordinates, it's not enough to check for TreatsAsLatLong. You also have to test for TreatsAsNorthingEasting which in that case I would expect to return false, and the order is "x", "y", so this is not an appropriate example as it is not flipped.
Why the EPSG:4326 system doesn't return True for the EPSGTreatsAsLatLong test is weird. You could ask that on OSGeo. But we should find a projected system which has northing-easting order.

**Comment by fsvieira** [comment]
Hi,

I checked the ogr code, and this is how it works:
int OGRSpatialReference::EPSGTreatsAsLatLong()
{
    if( !IsGeographic() )
        return FALSE;

```
const char *pszAuth = GetAuthorityName( "GEOGCS" );

if( pszAuth == NULL || !EQUAL(pszAuth,"EPSG") )
    return FALSE;

OGR_SRSNode *poFirstAxis = GetAttrNode( "GEOGCS|AXIS" );

if( poFirstAxis == NULL )
    return FALSE;

if( poFirstAxis->GetChildCount() >= 2 
    && EQUAL(poFirstAxis->GetChild(1)->GetValue(),"NORTH") )
    return TRUE;

return FALSE;
```

}

I tried EPSGTreatsAsLatLong also returns false for all examples.

Maybe I should add a flag for setting orientation if the method fails?

**Comment by fsvieira** [comment]
Ok,

I think I got it right this time, I am using the 
[importFromEPSGA    (int nCode)](http://www.gdal.org/classOGRSpatialReference.html#aaa6965a1df98cdc673dfb20697eab613)

And I converted one of my images to EPSG:4326 (https://github.com/fsvieira/map2covjson/blob/master/tests/test-4326.tif) the covjson is generated with y,x orientation and its displaying correctly with covjson viewer.

There is another method called importFromEPSG, but this one doesn't follow the official epsg orientation, and gives me x,y on /test-4326.tif file.

**Comment by letmaik** [comment]
Those functions look alright, but I noticed you also change the axis order in the "ranges" part. I think this is not right and has to be "y","x" in all cases. Which is confusing as you said that it worked with your EPSG:4326 conversion. Can you verify that?

**Comment by fsvieira** [comment]
Hi,

Yes I think you are right, what I was doing was to put the same axis order in both fields domain and ranges, so the 4326, so that worked ok because the axis order was y, x.

So, I tested with the other raster that gives me x,y and it was flipped, so I guess it clear the confusion. 
To fix it I change the line:
https://github.com/fsvieira/map2covjson/blob/master/map2covjson.cpp#L174

Is this right?
Thanks.

**Comment by letmaik** [comment]
Sorry I don't understand exactly what you tested and the results of it. The change you made is what I meant, yes. With that change, do all your test grids appear right in the covjson playground, that is, _not_ flipped? Nothing should be flipped, otherwise there's a problem.

**Comment by fsvieira** [comment]
I am testing the covjson with leaflet+covjson site that I put together on my localhost, then load the covjson data a check if it displays the same as in qgis program.

With the new changes nothing is flipped, and they are all displaying the same.

**Comment by letmaik** [comment]
OK, that's great then. I think this issue can be closed. For future reference, the [Apache SIS CRS codes](http://sis.apache.org/tables/CoordinateReferenceSystems.html) page lists many CRSs and indicates whether they are left-handed or not.
